# Generated by Django 5.0.1 on 2024-01-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("CarDealership", "0001_initial"),
        ("Dealer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablecarmodels",
            name="car_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dealer.carmodel",
                verbose_name="Model of car",
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="available_car_models",
            field=models.ManyToManyField(
                related_name="car_dealerships",
                through="CarDealership.AvailableCarModels",
                to="Dealer.carmodel",
                verbose_name="Models to sale",
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="dealership_cars",
            field=models.ManyToManyField(
                related_name="dealerships",
                through="Dealer.DealersSalesHistory",
                to="Dealer.dealercars",
                verbose_name="Dealership cars to sale",
            ),
        ),
        migrations.AddField(
            model_name="availablecarmodels",
            name="car_dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="list_car_model",
                to="CarDealership.cardealership",
                verbose_name="Car dealership",
            ),
        ),
        migrations.AddField(
            model_name="carsdiscount",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discounts",
                to="Dealer.car",
                verbose_name="Discount available for cars",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="car_dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discounts",
                to="CarDealership.cardealership",
                verbose_name="Discount for car dealership",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="cars",
            field=models.ManyToManyField(
                through="CarDealership.CarsDiscount",
                to="Dealer.car",
                verbose_name="Discount for cars",
            ),
        ),
        migrations.AddField(
            model_name="carsdiscount",
            name="discount",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="list_cars",
                to="CarDealership.discount",
                verbose_name="Discount",
            ),
        ),
        migrations.AddField(
            model_name="profitabledealers",
            name="car_dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profit_dealers",
                to="CarDealership.cardealership",
            ),
        ),
        migrations.AddField(
            model_name="profitabledealers",
            name="car_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dealer.carmodel",
                verbose_name="Profitable car models",
            ),
        ),
        migrations.AddField(
            model_name="profitabledealers",
            name="dealer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dealer.dealer",
                verbose_name="Profitable dealers",
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="profitable_dealers",
            field=models.ManyToManyField(
                related_name="car_dealership",
                through="CarDealership.ProfitableDealers",
                to="Dealer.dealer",
                verbose_name="Profitable dealers",
            ),
        ),
    ]
