# Generated by Django 5.0.3 on 2024-03-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CarDealership", "0001_initial"),
        ("Dealer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablecarmodels",
            name="car_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dealer.carmodel",
                verbose_name="Model of car",
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="car_models",
            field=models.ManyToManyField(
                related_name="in_dealership",
                through="CarDealership.AvailableCarModels",
                to="Dealer.carmodel",
                verbose_name="Models to sale",
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="dealership_cars",
            field=models.ManyToManyField(
                related_name="dealerships",
                through="Dealer.DealersSalesHistory",
                to="Dealer.dealercars",
                verbose_name="Dealership cars to sale",
            ),
        ),
        migrations.AddField(
            model_name="availablecarmodels",
            name="car_dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="list_car_model",
                to="CarDealership.cardealership",
                verbose_name="Car dealership",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="car_dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_discounts",
                to="CarDealership.cardealership",
                verbose_name="Discount for car dealership",
            ),
        ),
    ]
