version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - custom

  django:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000
                    && python manage.py makemigrations
                    && python manage.py migrate"
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - custom

volumes:
  postgresdb_data:

networks:
  custom:
    driver: bridge