version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - custom

  django:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - custom
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - custom
  
  celery:
    build: .
    container_name: celery
    command: celery -A DjangoProject worker -l info
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - django
      - redis
      - postgres
    networks:
      - custom
  
  celerybeat:
    build: .
    container_name: celerybeat
    command: celery -A DjangoProject beat -l info
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - celery
      - redis
      - postgres
    networks:
      - custom

volumes:
  postgresdb_data:

networks:
  custom:
    driver: bridge
